dist: bin

builds:
- env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - 386
    - amd64
    - arm
  goarm:
    - 6
    - 7
  ignore:
    - goos: darwin
      goarch: 386
  gcflags:
    - all=-trimpath={{.Env.GOPATH}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

source:
  enabled: true

release:
  prerelease: auto

checksum:
  name_template: checksums.txt

brews:
  - tap:
      owner: pkarpovich
      name: homebrew-shortcuts-remote-server
    commit_author:
      name: Pavel Karpovich
      email: pavel.karpovich@outlook.com
    homepage: https://github.com/pkarpovich/shortcuts-remote-server
    install: |
        bin.install "shortcuts-remote-server"

nfpms:
  -
    homepage: https://github.com/pkarpovich/shortcuts-remote-server
    maintainer: Pavek Karpovich <pavel.karpovich@outlook.com>
    formats:
      - deb
      - rpm
